# Generated by Django 5.1.3 on 2024-12-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
    ]
