# Generated by Django 4.2.7 on 2025-01-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_auth', '0002_alter_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='situacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
