# Generated by Django 5.1 on 2024-09-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_auth', '0002_alter_aluno_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.IntegerField(unique=True)),
                ('perfil', models.IntegerField(choices=[(1, 'Admin'), (2, 'Aluno'), (3, 'Professor')], default=2)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('situacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
