# Generated by Django 4.2.7 on 2024-12-01 22:19

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('dificuldade', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil')], default=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('banca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srciencia_core.banca')),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='srciencia_core.conteudo')),
            ],
        ),
        migrations.CreateModel(
            name='TopicoQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srciencia_core.questao')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srciencia_core.topico')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srciencia_core.disciplina')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srciencia_core.questao')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srciencia_core.conteudo')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srciencia_core.questao')),
            ],
        ),
        migrations.AddField(
            model_name='conteudo',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='srciencia_core.disciplina'),
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variaveis', models.JSONField(default=dict)),
                ('resolucao', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='srciencia_core.questao')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='alternativas/')),
                ('correta', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='srciencia_core.caso')),
            ],
        ),
    ]
