# Generated by Django 5.1.3 on 2024-12-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
