# Generated by Django 4.2.7 on 2024-10-28 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='dica',
            new_name='resolucao',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='pontuacao',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alternativa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='alternativas/'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alteravel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil')], default=1),
        ),
        migrations.AddField(
            model_name='questao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='questoes/'),
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='srciencia_core.conteudo')),
            ],
        ),
        migrations.AddField(
            model_name='conteudo',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='srciencia_core.disciplina'),
        ),
        migrations.AddField(
            model_name='questao',
            name='conteudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srciencia_core.conteudo'),
        ),
        migrations.AddField(
            model_name='questao',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srciencia_core.disciplina'),
        ),
        migrations.AddField(
            model_name='questao',
            name='topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srciencia_core.topico'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='banca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srciencia_core.banca'),
        ),
    ]
