# Generated by Django 5.1.3 on 2024-12-22 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0002_alter_turma_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='turmas_inscritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_criadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
