# Generated by Django 4.2.7 on 2024-10-28 19:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0002_banca_conteudo_disciplina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='questao',
            name='descricao',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(1, 'Fácil'), (3, 'Difícil'), (2, 'Médio')], default=1),
        ),
    ]
