# Generated by Django 5.1.3 on 2024-12-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0003_turma_alunos_alter_turma_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='alunos',
        ),
    ]
