# Generated by Django 4.2.7 on 2024-12-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0003_alter_questao_dificuldade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(3, 'Difícil'), (2, 'Médio'), (1, 'Fácil')], default=1),
        ),
    ]
