# Generated by Django 4.2.7 on 2024-12-01 23:26

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0003_alter_questao_dificuldade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='resolucao',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='resolucao'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='descricao',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(2, 'Médio'), (1, 'Fácil'), (3, 'Difícil')], default=1),
        ),
    ]
