# Generated by Django 5.1.3 on 2024-12-25 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0004_turmaaluno_alter_turma_alunos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos_v2',
            field=models.ManyToManyField(blank=True, related_name='turmas_inscritas_v2', through='srciencia_core.TurmaAluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='turmas_inscritas', to=settings.AUTH_USER_MODEL),
        ),
    ]
