# Generated by Django 5.1.3 on 2024-12-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0004_turmaaluno_alter_turma_alunos'),
        ('srciencia_core', '0005_turmaaluno_turma_alunos'),
    ]

    operations = [
    ]
