# Generated by Django 5.1.3 on 2024-12-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0005_turma_alunos_v2_alter_turma_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='alunos_v2',
        ),
    ]
