# Generated by Django 5.1.3 on 2024-12-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0006_remove_turma_alunos_remove_turma_alunos_v2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TurmaAluno',
        ),
    ]
