# Generated by Django 4.2.7 on 2024-12-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0005_alter_questao_dificuldade'),
        ('srciencia_core', '0007_arquivo'),
    ]

    operations = [
    ]
