# Generated by Django 4.2.7 on 2025-01-02 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srciencia_core', '0009_alter_questao_dificuldade'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='visualizado_por',
            field=models.ManyToManyField(blank=True, related_name='arquivos_visualizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
