# Generated by Django 4.2.7 on 2025-01-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0010_arquivo_visualizado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(1, 'Fácil'), (3, 'Difícil'), (2, 'Médio')], default=1),
        ),
    ]
