# Generated by Django 4.2.7 on 2025-01-04 05:21

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0012_alter_questao_dificuldade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(2, 'Médio'), (1, 'Fácil'), (3, 'Difícil')], default=1),
        ),
        migrations.AlterField(
            model_name='questao',
            name='resolucao',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='resolucao'),
        ),
    ]
