# Generated by Django 4.2.7 on 2025-01-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0013_alter_questao_dificuldade_alter_questao_resolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(3, 'Difícil'), (2, 'Médio'), (1, 'Fácil')], default=1),
        ),
    ]
