# Generated by Django 4.2.7 on 2025-01-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0015_alter_questao_dificuldade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
