# Generated by Django 4.2.7 on 2025-01-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0016_alter_alternativa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(3, 'Difícil'), (1, 'Fácil'), (2, 'Médio')], default=1),
        ),
    ]
