# Generated by Django 4.2.7 on 2025-01-08 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srciencia_core', '0017_alternativa_imagem_url_alter_questao_dificuldade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(2, 'Médio'), (1, 'Fácil'), (3, 'Difícil')], default=1),
        ),
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correta', models.BooleanField(default=False)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('alternativa_selecionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='srciencia_core.alternativa')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to=settings.AUTH_USER_MODEL)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='srciencia_core.questao')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_problema', models.TextField()),
                ('data_relatorio', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to=settings.AUTH_USER_MODEL)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='srciencia_core.questao')),
            ],
        ),
    ]
