# Generated by Django 4.2.7 on 2025-01-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0018_alter_questao_dificuldade_respostaaluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='taxa_acertos',
            field=models.FloatField(default=0, verbose_name='Taxa de Acertos (%)'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(3, 'Difícil'), (1, 'Fácil'), (2, 'Médio')], default=1),
        ),
    ]
