# Generated by Django 4.2.7 on 2025-01-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0019_questao_taxa_acertos_alter_questao_dificuldade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(2, 'Médio'), (1, 'Fácil'), (3, 'Difícil')], default=1),
        ),
    ]
