# Generated by Django 4.2.7 on 2025-01-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srciencia_core', '0022_alter_questao_dificuldade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(3, 'Difícil'), (1, 'Fácil'), (2, 'Médio')], default=1),
        ),
    ]
