# Generated by Django 4.2.7 on 2025-01-12 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srciencia_core', '0023_alter_questao_dificuldade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(2, 'Médio'), (3, 'Difícil'), (1, 'Fácil')], default=1),
        ),
        migrations.CreateModel(
            name='Resolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resolucao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolucoes', to=settings.AUTH_USER_MODEL)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolvido_por', to='srciencia_core.questao')),
            ],
        ),
    ]
