# Generated by Django 4.2.7 on 2025-01-18 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srciencia_core', '0025_alter_questao_dificuldade'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='favoritada_por',
            field=models.ManyToManyField(blank=True, related_name='questoes_favoritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(3, 'Difícil'), (2, 'Médio'), (1, 'Fácil')], default=1),
        ),
    ]
